const db = require('../db')
const { CondoUnit, UnitRep, UnitStyle } = require('../models')

db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
  //unit styles -- update names once styles are named!
  const bensyCottage = await UnitStyle.find({name: 'Bensy Cottage'})
  const tammyHome = await UnitStyle.find({name: 'Tammy Home'})
  const georgieFlair = await UnitStyle.find({name: 'Georgie Flair'})
  const dorseyVilla = await UnitStyle.find({name: 'Dorsey Villa'})

  //unit reps
  const robertPence = await UnitRep.find({name: 'Robert Pence'})
  const emilieLark = await UnitRep.find({name: 'Emilie Lark'})
  const teddyJones = await UnitRep.find({name: 'Teddy Jones'})
  const laraGomez = await UnitRep.find({name: 'Lara Gomez'})
  
  const condoUnits = [
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 1,
      unitImg: 'https://cdn.houseplansservices.com/content/89hpc610ashba3v941ih70oeq5/w991x660.jpg?v=9',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 1,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 20,
      unitImg: 'https://cdn.houseplansservices.com/content/89hpc610ashba3v941ih70oeq5/w991x660.jpg?v=9',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: false,
      sqFt: 950,
      beds: 2,
      baths: 1,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'East',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 13,
      unitImg: 'https://cdn.houseplansservices.com/content/1crartf4esqstardciellil6mh/w991x660.jpg?v=9',
      monthlyRent: 2200,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 1000,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: false,
      petRent: 0,
      petPolicy: 'N/A'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 4,
      unitImg: 'https://images.familyhomeplans.com/cdn-cgi/image/fit=scale-down,quality=85/plans/41438/41438-b580.jpg',
      monthlyRent: 2300,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 1100,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 45,
      petPolicy: 'Certain breed restrictions apply. Get in contact for more information'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 18,
      unitImg: 'https://cdn.houseplansservices.com/content/89hpc610ashba3v941ih70oeq5/w991x660.jpg?v=9',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: false,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'East',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: '$400 refundable deposit due prior to move-in.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 6,
      unitImg: 'https://www.thehousedesigners.com/images/uploads/SiteImage-Landing-two-story-house-plans-1.webp',
      monthlyRent: 2300,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 1050,
      beds: 3,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 45,
      petPolicy: '$400 refundable deposit due prior to move-in.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 7,
      unitImg: 'https://morguefile.nyc3.cdn.digitaloceanspaces.com/imageData/public/files/o/o0o0xmods0o0o/preview/fldr_2008_11_28/file000658805796.jpg',
      monthlyRent: 2150,
      deposit: "First and last month's rent required at signing.",
      available: false,
      sqFt: 1200,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 8,
      unitImg: 'https://coolhouseconcepts.com/wp-content/uploads/2018/11/01-11.jpg',
      monthlyRent: 3000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 2000,
      beds: 3,
      baths: 3,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 9,
      unitImg: 'https://cdn-5.urmy.net/images/plans/DSD/bulk/9089/front-elevation-2_1_m.jpg',
      monthlyRent: 3500,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 2200,
      beds: 4,
      baths: 3,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 15,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: false,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'East',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 10,
      unitImg: 'https://morguefile.nyc3.cdn.digitaloceanspaces.com/imageData/public/files/o/o0o0xmods0o0o/preview/fldr_2008_11_28/file000658805796.jpg',
      monthlyRent: 2200,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 2000,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: georgieFlair[0]._id,
      unitNumber: 11,
      unitImg: 'https://cdn11.bigcommerce.com/s-g95xg0y1db/images/stencil/1280x1280/x/townhouse%20plan%20-%2069835__95656.original.jpg',
      monthlyRent: 2600,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 2600,
      beds: 3,
      baths: 2.5,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: georgieFlair[0]._id,
      unitNumber: 12,
      unitImg: 'https://markstewart.com/wp-content/uploads/2014/07/MM-1887-FRONT-WEB-scaled.jpg',
      monthlyRent: 2750,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 2700,
      beds: 3,
      baths: 3,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'North',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: georgieFlair[0]._id,
      unitNumber: 3,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2850,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 2750,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 14,
      unitImg: 'https://cdn.houseplansservices.com/product/ahsl4dcgsv4in9ru6g3t1jrfcm/w620x413.png?v=11',
      monthlyRent: 3100,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 3000,
      beds: 4,
      baths: 3,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'East',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 16,
      unitImg: 'https://cdn.houseplansservices.com/product/ahsl4dcgsv4in9ru6g3t1jrfcm/w620x413.png?v=11',
      monthlyRent: 3400,
      deposit: "First and last month's rent required at signing.",
      available: false,
      sqFt: 3100,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'East',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 17,
      unitImg: 'https://cdn.houseplansservices.com/product/ahsl4dcgsv4in9ru6g3t1jrfcm/w620x413.png?v=11',
      monthlyRent: 2900,
      deposit: "First and last month's rent required at signing.",
      available: false,
      sqFt: 3000,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 2,
      location: 'East',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 5,
      unitImg: 'https://i.pinimg.com/736x/f4/24/0b/f4240b1058048af6ec9c6cb86a24db15.jpg',
      monthlyRent: 4500,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 3200,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 3,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 19,
      unitImg: 'https://www.probuilder.com/sites/default/files/DTJ-Mountain-Triplex-elevation-1.png',
      monthlyRent: 4550,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 3500,
      beds: 5,
      baths: 4,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 3,
      location: 'East',
      description: '',
      acceptsPets: false,
      petRent: 0,
      petPolicy: 'N/A'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 2,
      unitImg: 'https://i2.au.reastatic.net/800x600/0f1fd587c7f1d444fc140b33547cac5bfe6943e9469584260e30914822486e59/main.jpg',
      monthlyRent: 4750,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 4500,
      beds: 5,
      baths: 5,
      utilitiesAvailable: ['water','electricity', 'gas', 'trash', 'sewage','landline','internet'],
      parkingSpaces: 3,
      location: 'West',
      description: '',
      acceptsPets: false,
      petRent: 50,
      petPolicy: 'N/A'
    }
  ]
 
  await CondoUnit.insertMany(condoUnits)

  console.log('Created condominium units!')
}

const run = async () => {
  await main()
  db.close()
}

run()