const db = require('../db')
const { CondoUnit, UnitRep, UnitStyle } = require('../models')

db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {
  //unit styles -- update names once styles are named!
  const bensyCottage = await UnitStyle.find({name: 'Bensy Cottage'})
  const tammyHome = await UnitStyle.find({name: 'Tammy Home'})
  const georgieFlair = await UnitStyle.find({name: 'Georgie Flair'})
  const dorseyVilla = await UnitStyle.find({name: 'Dorsey Villa'})

  //unit reps
  const robertPence = await UnitRep.find({name: 'Robert Pence'})
  const emilieLark = await UnitRep.find({name: 'Emilie Lark'})
  const teddyJones = await UnitRep.find({name: 'Teddy Jones'})
  const laraGomez = await UnitRep.find({name: 'Lara Gomez'})
  
  const condoUnits = [
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 1,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 1,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 20,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 1,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 13,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 4,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 18,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: robertPence[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 6,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 3,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 7,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 8,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 3,
      baths: 3,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 9,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 4,
      baths: 3,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: teddyJones[0]._id,
      unitStyle_id: bensyCottage[0]._id,
      unitNumber: 15,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: tammyHome[0]._id,
      unitNumber: 10,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 2,
      baths: 2,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: georgieFlair[0]._id,
      unitNumber: 11,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 3,
      baths: 2.5,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: georgieFlair[0]._id,
      unitNumber: 12,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 3,
      baths: 3,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: georgieFlair[0]._id,
      unitNumber: 3,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 14,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 4,
      baths: 3,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: laraGomez[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 16,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 17,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 5,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 4,
      baths: 4,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 19,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 5,
      baths: 4,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    },
    {
      unitRep_id: emilieLark[0]._id,
      unitStyle_id: dorseyVilla[0]._id,
      unitNumber: 2,
      unitImg: 'unitImgUrlHere.com',
      monthlyRent: 2000,
      deposit: "First and last month's rent required at signing.",
      available: true,
      sqFt: 950,
      beds: 5,
      baths: 5,
      utilitiesAvailable: ['',''],
      parkingSpaces: 1,
      location: 'West',
      description: '',
      acceptsPets: true,
      petRent: 50,
      petPolicy: 'Either $500 non-refundable deposit with $25/month per pet fee for the duration of the contract or $50/month per pet.'
    }
  ]
 
  await CondoUnit.insertMany(condoUnits)

  console.log('Created condominium units!')
}

const run = async () => {
  await main()
  db.close()
}

run()